### ISSUE TITLE
可以加一个docker的启动教程吗

### ISSUE THREAD

**Issue by danelking** [Leizhenpeng/feishu-chatGpt#1]
serverless没有环境，谢谢拉

**Comment by Leizhenpeng** [comment]
> serverless没有环境，谢谢拉

思考一下哈哈、主要是飞书的事件订阅需要公网ip，后面我加一下docker部署😉

**Comment by binlyliu** [comment]
同求，希望出个docker配置

**Comment by Leizhenpeng** [comment]
已支持啦~ 

https://github.com/Leizhenpeng/feishu-chatGpt/pull/3
