### ISSUE TITLE
🐞 错误报告  handlers common.go中的ASCII码 转换有错误

### ISSUE THREAD

**Issue by snailq** [Leizhenpeng/feishu-chatgpt#100]
handlers common.go中的ASCII码	转换有错误会导致大于号小于号打印成数字
`func processUnicode(msg string) string {
	regex := regexp.MustCompile(`\\u[0-9a-fA-F]{4}`)
	return regex.ReplaceAllStringFunc(msg, func(s string) string {
		r, _ := regexp.Compile(`\\u`)
		s = r.ReplaceAllString(s, "")
		i, _ := strconv.ParseInt(s, 16, 32)
		//return strconv.Itoa(int(i))
                //应该改成这个吧
		return string(rune(i))
	})
}`

**Comment by Leizhenpeng** [comment]
要不给个pr哈哈
