### ISSUE TITLE
🐞 错误报告 才使用了几分钟，chatgpt 账号就被封了

### ISSUE THREAD

**Issue by calfzhou** [Leizhenpeng/feishu-chatgpt#102]
# 错误报告 🐞

## 错误描述 🤔

在本机跑 docker 起的服务，通过服务器的 ip 地址反向代理回到本机服务，配置好了之后，先发了两条对话文本消息，都正常给出回应，然后尝试图片创作模式，选择分辨率为 512x512，给了一段提示文案「满脸沧桑的老人，坐在窗前藤椅上，看着自己满是茧的双手。」，然后账号就被禁用了：

This key is associated with a deactivated account.

## 附加信息 📝

请提供以下信息以帮助我们更快地解决问题：

- 输出日志，包括错误信息和堆栈跟踪
<img width="1297" alt="image" src="https://user-images.githubusercontent.com/3761553/225835074-d5a9db10-9596-4578-8938-7f28f1ee4966.png">

- 相关的代码片段或文件
- 您的操作系统、软件版本等环境信息

<img width="696" alt="image" src="https://user-images.githubusercontent.com/3761553/225835149-0a908853-2163-4487-b44d-7896a51f4961.png">

还有人遇到这种情况吗？机器人都还没有开放使用，才刚刚调试一下下而已……

**Comment by Leizhenpeng** [comment]
遇到过

解决办法是：给openai 氪金

😩

**Comment by sytpb** [comment]
mark 一下，什么原因被封？

**Comment by calfzhou** [comment]
没说特别具体的，就说是违反了他们的政策，就发了上面截图的那个邮件。

不过幸运的是，前两天突然又给恢复了~~ 但不敢再调 api 了。我自己另一个账号就没遇到问题，已经用了小一个月了，还没被封。

**Comment by sytpb** [comment]
感觉是识别你的访问来自(unsupported location),  不太理解，你的服务器是哪个地区（国家）， 不是做了反向代理吗？怎么被识别出来了。

**Comment by calfzhou** [comment]
美国的代理，国内访问 api 好像直接就访问不了，印象中已经被防火墙拦住了。而且后来换了个账号，也是用的一样的代理，就挺奇怪的。

**Comment by sytpb** [comment]
哦，两个账号配置都一样？ 都没有付费？

**Comment by sytpb** [comment]
美国的代理--自己部的服务器？
