### ISSUE TITLE
最新的镜像使用的模型是gpt-3.5-turbo-0301

### ISSUE THREAD

**Issue by xavi713** [Leizhenpeng/feishu-chatgpt#106]
# 错误报告 🐞

如果您在使用此项目时遇到了错误，请在此报告，我们会尽快解决此问题。

## 错误描述 🤔

不确定是不是错误，现在使用的模型是gpt-3.5-turbo-0301，不是gpt-3.5-turbo

## 附加信息 📝
<img width="400" alt="image" src="https://user-images.githubusercontent.com/44320524/226793154-ba27fd6a-07f0-44a6-95da-1e0b0e04ba8c.png">

请提供以下信息以帮助我们更快地解决问题：

- 输出日志，包括错误信息和堆栈跟踪
- 相关的代码片段或文件
- 您的操作系统、软件版本等环境信息

感谢您的反馈！🙏

**Comment by Leizhenpeng** [comment]
My understanding is that gpt-3.5-turbo will always be the latest model, which is gpt-3.5-turbo-0301 as of now. 

https://community.openai.com/t/attempting-to-use-gpt-3-5-turbo-getting-gpt-3-5-turbo-0301-instead/94411/4

**Comment by xavi713** [comment]
谢谢回复，所以目前调用chatgpt的api其实是用的gpt-3.5-turbo-0301这个模型？
