### ISSUE TITLE
🐞 错误报告：ping可以获得200反馈，但是webhook/event就是 404，这是为什么

### ISSUE THREAD

**Issue by neohob** [Leizhenpeng/feishu-chatgpt#109]
# 错误报告 🐞

ping可以获得200反馈，但是webhook/event就是 404

## 错误描述 🤔

ping可以获得200反馈，但是webhook/event就是 404

## 附加信息 📝

请提供以下信息以帮助我们更快地解决问题：

[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /ping                     --> main.main.func2 (3 handlers)
[GIN-debug] POST   /webhook/event            --> github.com/larksuite/oapi-sdk-gin.NewEventHandlerFunc.func1 (3 handlers)
[GIN-debug] POST   /webhook/card             --> github.com/larksuite/oapi-sdk-gin.NewCardActionHandlerFunc.func1 (3 handlers)
2023/03/22 17:55:38 http server started: http://localhost:9000/webhook/event
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on :9000
[GIN] 2023/03/22 - 18:00:51 | 404 |         601ns |  xxxxx | GET      "/event/card"
[GIN] 2023/03/22 - 18:01:04 | 404 |         831ns |  xxxxx | GET      "//webhook/event"
[GIN] 2023/03/22 - 18:01:11 | 404 |         802ns |  xxxxx | GET      "/webhook/event"
[GIN] 2023/03/22 - 18:05:53 | 404 |         972ns |       127.0.0.1 | GET      "/webhook/card"
[GIN] 2023/03/22 - 18:06:11 | 404 |         902ns |       127.0.0.1 | GET      "/webhook/event"
[GIN] 2023/03/22 - 18:06:16 | 404 |         641ns |       127.0.0.1 | GET      "/webhook/event"
[GIN] 2023/03/22 - 18:06:31 | 404 |         831ns |  xxxxxx | GET      "/"
[GIN] 2023/03/22 - 18:07:58 | 200 |      97.342µs |  xxxxxx | GET      "/ping"
[GIN] 2023/03/22 - 18:08:11 | 404 |         901ns |  xxxxx | GET      "/webhook/event"
[GIN] 2023/03/22 - 18:08:13 | 404 |         692ns | xxxxx| GET      "/webhook/event"
[GIN] 2023/03/22 - 18:08:27 | 404 |         922ns |  xxxxx | GET      "//webhook/event"
[GIN] 2023/03/22 - 18:08:34 | 404 |         952ns |  xxxxx | GET      "/webhook/event"
[GIN] 2023/03/22 - 18:08:47 | 404 |         581ns | xxxxx | GET      "/webhook/event/"
[GIN] 2023/03/22 - 18:08:52 | 200 |      35.036µs |  xxxxx | GET      "/ping"
[GIN] 2023/03/22 - 18:09:52 | 404 |         911ns | xxxxx| GET      "/event/card"

感谢您的反馈！🙏

**Comment by neohob** [comment]
哦，看到post才有200

**Comment by huangpd** [comment]
大佬我也一样
