### ISSUE TITLE
x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by lewis-huang** [Leizhenpeng/feishu-chatGpt#11]
大佬们：都走到这一步了，换了好几个 openAI 的 Key 都不行。我能确定这些 key 都没过期

![image](https://user-images.githubusercontent.com/11453153/218329605-cd11362b-0c55-47a7-ab84-1addfe7a094d.png)

{
    "error": {
        "message": "You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}

补充下部署的背景：
1. 在 Bandwagon 的 VPS 上，本地部署了本项目
2. 这台 VPS 可以打开 chat.openai.com 进行会话
3. Encrypt Key/Verfication Token: 打开或关闭，都试过
4. 2 个 openAI Key 都还有余额可用
5. 直接运行 go run main.go 执行

谢谢

**Comment by Dishone** [comment]
If your device’s time is not correct, you may run into SSL connection issues throughout the web because some SSL certificates rely on internal system clocks for validation. An incorrect time or date on your computer can lead to errors as your browser can’t verify these certificates

**Comment by lewis-huang** [comment]
Emmm, I still cannot resolve the certificate issue.
And later I reinstalled the whole CentOS7 system and get it run successfully

Now the bugs are coming, like duplicated response messages, gtp api 503 Service Unavailable, and so on
