### ISSUE TITLE
🐞 错误报告

### ISSUE THREAD

**Issue by hfdptech** [Leizhenpeng/feishu-chatgpt#111]
# 错误报告 🐞

[Error] [handle event,path:/webhook/event, error:runtime error: invalid memory address or nil pointer dereference]

## 错误描述 🤔

偶尔会报错，现象是在飞书上发消息，没有响应。

## 附加信息 📝

请提供以下信息以帮助我们更快地解决问题：

- 输出日志，包括错误信息和堆栈跟踪
- 相关的代码片段或文件
- 您的操作系统、软件版本等环境信息

感谢您的反馈！🙏

**Comment by moxiaolong** [comment]
一样

**Comment by Leizhenpeng** [comment]
openai的token失效~

**Comment by hfdptech** [comment]
我用的是新加坡和美国的服务器。

**Comment by skycsky** [comment]
同上，我的apikey是有效的，自己部署的网页端可以正常使用
