### ISSUE TITLE
🐞 错误报告 event type: message, not found handler

### ISSUE THREAD

**Issue by muuyao** [Leizhenpeng/feishu-chatgpt#112]
## 错误描述 🤔

部署在 railway 上，有时候飞书没有响应，报如下的错误

[Error] [handle event,path:/webhook/event,error:event type: message, not found handler]

感谢您的反馈！🙏

**Comment by reallyli** [comment]
同报错，
![image](https://user-images.githubusercontent.com/24422856/227791338-7f3fc93e-fc78-4e22-b2a6-107832d468ee.png)

**Comment by Leizhenpeng** [comment]
请检查飞书开发者平台的后台参数还有时间订阅权限是否开启

**Comment by see2** [comment]
同报错：
2023/03/27 07:48:30 [Error] [handle event,path:/webhook/event,error:event type: message, not found handler] [GIN] 2023/03/27 - 07:48:30 | 200 |  868.930332ms |   123.58.10.239 | POST     "/webhook/event"

群聊就会发生这个问题，事件订阅确认开启，权限管理开启。

**Comment by Verystone** [comment]
please remove event
![image](https://user-images.githubusercontent.com/50290954/227903474-c8e28dad-6113-4227-b617-e0000e9468f2.png)

**Comment by GoingMyWay** [comment]
> please remove event ![image](https://user-images.githubusercontent.com/50290954/227903474-c8e28dad-6113-4227-b617-e0000e9468f2.png)

有效。

**Comment by reallyli** [comment]
已经移除了
