### ISSUE TITLE
Railway 部署，聊天没有反应

### ISSUE THREAD

**Issue by FormatToday** [Leizhenpeng/feishu-chatgpt#117]
# 问题交流 💬

## 问题描述 🤔

使用railway部署，按照文档来的，也审核上线了，但是机器人私聊和群聊都没有回复

## 附加信息 📝
railway也没有响应的日志
![image](https://user-images.githubusercontent.com/20515769/227446405-9807ebd5-8e4a-4ab8-9f09-ab226466bcfb.png)

**Comment by pomnb** [comment]
+1

**Comment by zhaoleigege** [comment]
需要在飞书开放平台的 `开发配置` -> `事件订阅` -> `已添加事件` 中点击`添加事件`搜索`接收消息`然后重新发布一个新版本就可以了

**Comment by Leizhenpeng** [comment]
检查一下飞书开发者平台上的事件订阅以及参数是否配置正确

**Comment by T4di5** [comment]
+1

> > 需要在飞书开放平台的 `开发配置` -> `事件订阅` -> `已添加事件` 中点击`添加事件`搜索`接收消息`然后重新发布一个新版本就可以了
> 
> ![image](https://user-images.githubusercontent.com/20515769/227887961-873ba629-3271-49dc-a59c-2bcd8ff4f05c.png)
> 
> 现添加了之后，可以私聊，群聊还是不行

+1
