### ISSUE TITLE
群聊

### ISSUE THREAD

**Issue by 283859691** [Leizhenpeng/feishu-chatGpt#12]
发送群聊消息还是不会相应

**Comment by Leizhenpeng** [comment]
必须先@机器人

**Comment by 283859691** [comment]
我@机器人了，但是还是无法回复，且在docker日志里看到确实有流量写入容器里
chatType: group[GIN] 2023/02/16 - 09:33:12 | 200 |   29.778816ms |   123.58.10.238 | POST     "/webhook/event"

**Comment by loliuy** [comment]
我也是
