### ISSUE TITLE
请问是否支持gpt4

### ISSUE THREAD

**Issue by xavi713** [Leizhenpeng/feishu-chatgpt#125]
请问如果把模型换成4，账号是plus，是否就可以调用4的api了

**Comment by Leizhenpeng** [comment]
chatgpt和openai的api是两套账户，互相独立。

我暂时没有获准调用gpt4的api资格，项目暂时没有匹配gpt4的api接口、

**Comment by qdsang** [comment]
https://github.com/Leizhenpeng/feishu-chatgpt/blob/master/code/services/openai/gpt3.go#L10

我发现这改成 gpt-4 就可以了，用着没啥问题
        engine      = "gpt-4"

**Comment by T4di5** [comment]
> https://github.com/Leizhenpeng/feishu-chatgpt/blob/master/code/services/openai/gpt3.go#L10

那请求的是gpt-4吗？

**Comment by qdsang** [comment]
> > https://github.com/Leizhenpeng/feishu-chatgpt/blob/master/code/services/openai/gpt3.go#L10
> 
> 那请求的是gpt-4吗？

返回的模型是 gpt-4
