### ISSUE TITLE
报错 error:event type: message, not found handler，并存在空指针问题

### ISSUE THREAD

**Issue by reallyli** [Leizhenpeng/feishu-chatgpt#128]
@Leizhenpeng 

问题描述：首次部署，阿里云服务器，callback 验证 OK，但无法收到机器人发送的消息，权限都已经勾选了。

![image](https://user-images.githubusercontent.com/24422856/227791338-7f3fc93e-fc78-4e22-b2a6-107832d468ee.png)

_Originally posted by @reallyli in https://github.com/Leizhenpeng/feishu-chatgpt/issues/112#issuecomment-1484156088_

**Comment by Leizhenpeng** [comment]
请检查飞书机器人后台的事件订阅还有权限
