### ISSUE TITLE
请问这个repo支持lark吗？

### ISSUE THREAD

**Issue by GoingMyWay** [Leizhenpeng/feishu-chatgpt#137]
请问这个repo支持lark吗？应该没多大差异对吗？

**Comment by Leizhenpeng** [comment]
我就是lark写的呀。。。啥意思。。。

**Comment by GoingMyWay** [comment]
> 我就是lark写的呀。。。啥意思。。。

Lark是飞书的国际版，想问一下目前的这个repo是否支持Lark呢？
