### ISSUE TITLE
🚀 功能改善

### ISSUE THREAD

**Issue by xziye** [Leizhenpeng/feishu-chatgpt#163]
# 功能改善建议 🚀

欢迎在此分享您对功能的改善建议，我们期待听到您的想法和建议。

## 您的建议是什么？ 🤔

promopt是否会与角色扮演冲突？
如果不冲突建议支持设定全局prompt，储存起来，每次新建话题消息将prompt也发给openai接口

感谢您的分享和支持！🙏

**Comment by Leizhenpeng** [comment]
已在路线规划图中，常用角色~
