### ISSUE TITLE
🐞 错误报告 群聊对话模式无反应

### ISSUE THREAD

**Issue by Maple1401** [Leizhenpeng/feishu-chatgpt#172]
# 错误报告 🐞

只能开启第一次问题，后续在群聊中点击卡片的回复都没有反应。 单聊正常。

## 错误描述 🤔

![image](https://user-images.githubusercontent.com/10264395/229468377-117e256d-bc60-4126-aa2e-792e41f0da56.png)

然后就没有然后了

**Comment by Leizhenpeng** [comment]
群聊需要@机器人
