### ISSUE TITLE
是否支持群聊@机器人，机器人回复@消息

### ISSUE THREAD

**Issue by jujunchen** [Leizhenpeng/feishu-chatGpt#2]
是否支持群聊里@机器人，机器人回复@消息

**Comment by Leizhenpeng** [comment]
还在WIP， 即将支持~

**Comment by Leizhenpeng** [comment]
已支持

![image2](https://user-images.githubusercontent.com/50035229/218004853-423cd497-87e2-4611-8369-6c838246fa3a.png)

**Comment by Leizhenpeng** [comment]
@
