### ISSUE TITLE
Challenge code没有返回

### ISSUE THREAD

**Issue by coolhackboy** [Leizhenpeng/feishu-chatGpt#34]
Docker部署，ping 显示成功，返回
{
"message": "pong"
}，但是配置webhook/event 时候显示：Challenge code没有返回
查看容器日志
<img width="759" alt="image" src="https://user-images.githubusercontent.com/13427145/222941323-75206c5c-ce25-4ebb-80b8-72e13063b4f2.png">

求助？？？

**Comment by Leizhenpeng** [comment]
请检查飞书参数

**Comment by coolhackboy** [comment]
你的邮箱我已经收到了,有空我会看的

**Comment by coolhackboy** [comment]
增加了 Encrypt Key 配置 就可以了
