### ISSUE TITLE
🚀 功能改善 - 优化 图片创作 模式

### ISSUE THREAD

**Issue by designMe2023** [Leizhenpeng/feishu-chatgpt#49]
# 功能改善建议 🚀

可以根据用户文本描述，生成新的图片

## 您的建议是什么？ 🤔

1.  设立使用DALL·E接口的图片生成模式
2. 文字回复 `图片创作`或者`/picture`进入该模式。
3. 在该模式下
- 用户发送文字，AI将创建新的图片，
- 用户发送图片，则可以让AI寻找此图片的变体 🚧
- 结合消息卡片的交互能力，允许AI多次返回图片
- 用户框选图像的特定部分，AI将自动微调该区域以生成更准确的图像 🚧

6. 如需关闭该模式，用户可发送`清除`或`/clear`命令。

**Comment by Leizhenpeng** [comment]
希望可以结合消息卡片交互能力，同一文字允许生成多张图片
