### ISSUE TITLE
🚀 功能改善 - 允许代理访问openai

### ISSUE THREAD

**Issue by Leizhenpeng** [Leizhenpeng/feishu-chatgpt#54]
# 功能改善建议 🚀

国内服务器无法访问OpenAI的接口，需要配置代理才能继续提供服务。

## 您的建议是什么？ 🤔

1.  建议在OpenAI接口调用逻辑中加入代理配置选项，以便国内用户能够顺利使用OpenAI的服务。
2. 在文档中提供更详细的代理配置说明，以便开发者更好地理解和应用代理配置。

具体来说，可以提供如下内容：

- 代理的配置方法和相关参数
- 如何验证代理配置是否生效
- 常见代理配置问题和解决方案
- 通过提供详细的代理配置说明

感谢您的分享和支持！🙏

**Comment by Leizhenpeng** [comment]
看着🌟数还比较放心

**Comment by trevorwang** [comment]
这个是官方推荐的三方库
