### ISSUE TITLE
🚰 部署问题反馈 - 请求地址报错"Challenge code没有返回"

### ISSUE THREAD

**Issue by lingzwang** [Leizhenpeng/feishu-chatgpt#58]
docker 部署，ping显示成功，但是在配置请求地址的时候报Challenge code没有返回

docker日志报错如下：

![Pasted image 20230307153431](https://user-images.githubusercontent.com/42690430/223355646-2d29bf35-ed26-4f10-ba77-bab73df82e0a.png)

飞书参数正常，ID,SECRET,ENCRYPT_KEY,VERIFICATION_TOKEN,NAME都正常。

会不会是不是我服务器的ip被 openai 禁掉了？

**Comment by Leizhenpeng** [comment]
Challenge code报错应该只是飞书和你的服务器之间交互，不涉及openai

这种检查一下参数飞书的参数是否全部匹配

**Comment by lingzwang** [comment]
在飞书管理后台填错了地址。

在飞书机器人后台的机器人板块，填写消息卡片请求网址。

机器人板块下 填写 /webhook/card
![image](https://user-images.githubusercontent.com/42690430/223453953-60aa86a2-f051-49ca-ba9f-fd87ede8bd56.png)
