### ISSUE TITLE
📝 文档改善-希望可以增加非大陆地区免费serverless平台的部署教程。

### ISSUE THREAD

**Issue by ac123321** [Leizhenpeng/feishu-chatgpt#61]
# 文档改善建议 📝

希望可以增加非大陆地区免费serverless平台的部署教程。

**Comment by Leizhenpeng** [comment]
## For Example:
 Google func ,aws, vercel, azure, netlify, vercel...

**Comment by learningpro** [comment]
any plan on other platform?
