### ISSUE TITLE
🔧 项目维护

### ISSUE THREAD

**Issue by Andrew201801** [Leizhenpeng/feishu-chatgpt#68]
# 项目维护问题和建议 🔧

希望发布新版本时，同时发布升级指南，比如这次从beta版升级上来，应该是需要给机器人多申请一些权限

## 您的问题或建议是什么？ 🤔

在release中添加升级指南

## 您期望的解决方案是什么？ 💡

在release中添加升级指南

**Comment by Leizhenpeng** [comment]
谢谢~ 很实用的建议，下一版的release会增加升级指南
