### ISSUE TITLE
🐞 错误报告

### ISSUE THREAD

**Issue by livebei12** [Leizhenpeng/feishu-chatgpt#69]
# 错误报告 🐞

We assess our suggested \
ame using the extensively employed PCQM4MV2 benchmark dataset \\citep{DBLP:conf/nips/HuFRNDL21}, which involves predicting the HOMO-LUMO gap using molecular SMILES.
## 错误描述 🤔

转义符有点问题，这个 \name 变成 “换行” ame， 然后 citep 那边多了斜杠，大佬有空帮忙改下

## 附加信息 📝

请提供以下信息以帮助我们更快地解决问题：

- 输出日志，包括错误信息和堆栈跟踪
- 相关的代码片段或文件
- 您的操作系统、软件版本等环境信息

感谢您的反馈！🙏

**Comment by Leizhenpeng** [comment]
和 #65 合并处理~
