### ISSUE TITLE
阿里云-serverless云函数-部署问题反馈

### ISSUE THREAD

**Issue by taoxiaojin** [Leizhenpeng/feishu-chatgpt#72]
## 问题描述 🤔

阿里云-serverless云函数部署，部署成功后，发送消息时，serverless 相应报错。

主要报错为：
` Error: Invocation canceled by client (duration: 3565ms, maxMemoryUsage: 10.28MB)`

报错详情为：
`FC Invoke Start RequestId: 1-640989e8-936acbdf3b8483e00bdfced1
c-640989d0-383d2d6655aa4c7f80d12023-03-09 15:25:29chatType: p2p2023/03/09 07:25:28 request gtp json string : {"model":"gpt-3.5-turbo","messages":[{"role":"user","content":"什么是分离关注点"}],"max_tokens":2000,"temperature":0.7,"top_p":1,"frequency_penalty":0,"presence_penalty":0}
c-640989d0-383d2d6655aa4c7f80d12023-03-09 15:25:32FC Invoke End RequestId: 1-640989e8-936acbdf3b8483e00bdfced1, Error: Invocation canceled by client (duration: 3565ms, maxMemoryUsage: 10.28MB)
c-640989ed-2b0982ca9cf3446a8ccd2023-03-09 15:25:34[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /ping                     --> main.main.func2 (3 handlers)
[GIN-debug] POST   /webhook/event            --> github.com/larksuite/oapi-sdk-gin.NewEventHandlerFunc.func1 (3 handlers)
[GIN-debug] POST   /webhook/card             --> github.com/larksuite/oapi-sdk-gin.NewCardActionHandlerFunc.func1 (3 handlers)
http server started http://localhost:9000/webhook/event
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on :9000`

**Comment by Leizhenpeng** [comment]
打包的时候应该出现了问题，请参考 readme 中 severless 部分内容，重新打包
