### ISSUE TITLE
群聊@机器人不回复消息

### ISSUE THREAD

**Issue by devillee** [Leizhenpeng/feishu-chatGpt#8]
群聊@机器人不能回复消息，私聊@正常，不加@也正常

**Comment by Leizhenpeng** [comment]
可以看一下环境变量 config.yaml 里面的机器人名称和你自己在飞书后台里面定义的名称是不是一样的。

**Comment by devillee** [comment]
> 可以看一下环境变量 config.yaml 里面的机器人名称和你自己在飞书后台里面定义的名称是不是一样的。

不行，群聊机器人的名称就叫chatgpt, config里面也是chatgpt ，对了，我是基于master分支搭建的

**Comment by devillee** [comment]
> 可以看一下环境变量 config.yaml 里面的机器人名称和你自己在飞书后台里面定义的名称是不是一样的。

sorry，key 我看成BOTNAME 少加了个下划线
