### ISSUE TITLE
🐞 通过本地docker方式部署 配置完了之后 发现和机器人对话无相应

### ISSUE THREAD

**Issue by parkerqian** [Leizhenpeng/feishu-chatgpt#81]
这个是docker启动之后，启动的命令是这样的
docker run -d --name feishu-chatgpt -p 9000:9000 \
--env APP_ID=xxx \
--env APP_SECRET=xx \
--env APP_ENCRYPT_KEY=xx \
--env APP_VERIFICATION_TOKEN=xx \
--env BOT_NAME=chatGpt \
--env OPENAI_KEY="sk-xx,sk-xxx" \
--env API_URL="https://api.openai.com" \
feishu-chatgpt:latest
没有带http_proxy ，因为我本地能访问的通我的VPS机器
<img width="520" alt="image" src="https://user-images.githubusercontent.com/4987818/224296389-0baadd15-e0a3-4239-be55-935d2910a5e2.png">

![image](https://user-images.githubusercontent.com/4987818/224295818-1c17e507-c768-4fb9-bc5a-322bc101a159.png)

事件订阅
![image](https://user-images.githubusercontent.com/4987818/224295990-bfca6d13-2e58-4c2f-a775-0354c32ae914.png)

机器人配置
![image](https://user-images.githubusercontent.com/4987818/224296121-7df72e38-6571-49cb-9cb3-e1a238989c1d.png)

**Comment by parkerqian** [comment]
@Leizhenpeng 大佬能帮忙看下 我是哪步操作有问题么

**Comment by parkerqian** [comment]
你看上面截图 telnet ip +端口都通的

**Comment by Leizhenpeng** [comment]
飞书和vps无法通信，尝试更换亚洲vps。
