### ISSUE TITLE
能否把私聊机器人的逻辑改成不用回复上下文🚀 功能改善

### ISSUE THREAD

**Issue by viazry** [Leizhenpeng/feishu-chatgpt#93]
由于可以使用清除会话的功能，私聊没必要保留回复才能使用上下文关系
能不能直接对话也保留历史对话记录，在清除的时候才新建会话

**Comment by Leizhenpeng** [comment]
用户非常重视多话题对话的需求，我们为您带来了全新的多话题对话功能。
现在您可以将每个话题视为chatGpt左侧的一个tab栏，无论是私聊还是群聊，每个话题都可以独立对话。

如果您想保持对话连续，而不必在私聊中单独点击回复，请点击“x 条回复”按钮，进入回复栏中参与问答即可。

**Comment by Leizhenpeng** [comment]
后续, 在管理员模式下，可以关闭私人对话下的`多话题模式`
